vich_uploader:
    db_driver: orm
    
    metadata:
        type: attribute

    mappings:
        profileImages:
            uri_prefix: /uploads/userImages
            upload_destination: '%kernel.project_dir%/public/uploads/userImages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
